/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    '/[...NotFound]': RouteRecordInfo<'/[...NotFound]', '/:NotFound(.*)', { NotFound: ParamValue<true> }, { NotFound: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/account/login', Record<never, never>, Record<never, never>>,
    '/admin/hub': RouteRecordInfo<'/admin/hub', '/admin/hub', Record<never, never>, Record<never, never>>,
    '/admin/manage/resources': RouteRecordInfo<'/admin/manage/resources', '/admin/manage/resources', Record<never, never>, Record<never, never>>,
    '/admin/manage/resources.[Keyword]': RouteRecordInfo<'/admin/manage/resources.[Keyword]', '/admin/manage/resources/:Keyword', { Keyword: ParamValue<true> }, { Keyword: ParamValue<false> }>,
    '/stats/': RouteRecordInfo<'/stats/', '/stats', Record<never, never>, Record<never, never>>,
  }
}
