/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavLink: typeof import('./src/components/navigation/AdminNavLink.vue')['default']
    AdminNavLinkBanner: typeof import('./src/components/navigation/AdminNavLinkBanner.vue')['default']
    AdminNavLinks: typeof import('./src/components/navigation/AdminNavLinks.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CreateNewResourceButton: typeof import('./src/components/resources/CreateNewResourceButton.vue')['default']
    GoverningBodies: typeof import('./src/components/resources/GoverningBodies.vue')['default']
    GoverningBodiesTable: typeof import('./src/components/resources/tables/GoverningBodiesTable.vue')['default']
    GoverningBody: typeof import('./src/components/resources/forms/GoverningBodyForm.vue')['default']
    GoverningBodyForm: typeof import('./src/components/resources/forms/GoverningBodyForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeagueForm: typeof import('./src/components/resources/forms/LeagueForm.vue')['default']
    Leagues: typeof import('./src/components/resources/Leagues.vue')['default']
    LeaguesTable: typeof import('./src/components/resources/tables/LeaguesTable.vue')['default']
    LoginForm: typeof import('./src/components/authentication/LoginForm.vue')['default']
    ResourcesTable: typeof import('./src/components/resources/resourcesTable.vue')['default']
    ResourceTableSearch: typeof import('./src/components/resources/tables/ResourceTableSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    SportForm: typeof import('./src/components/resources/forms/SportForm.vue')['default']
    Sports: typeof import('./src/components/resources/Sports.vue')['default']
    SportsTable: typeof import('./src/components/resources/tables/SportsTable.vue')['default']
  }
}
