/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...notFound]': RouteRecordInfo<'/[...notFound]', '/:notFound(.*)', { notFound: ParamValue<true> }, { notFound: ParamValue<false> }>,
    'login': RouteRecordInfo<'login', '/account/login', Record<never, never>, Record<never, never>>,
    'hub': RouteRecordInfo<'hub', '/hub', Record<never, never>, Record<never, never>>,
    'resources': RouteRecordInfo<'resources', '/manage/resources', Record<never, never>, Record<never, never>>,
    '/manage/resources.[keyword]': RouteRecordInfo<'/manage/resources.[keyword]', '/manage/resources/:keyword', { keyword: ParamValue<true> }, { keyword: ParamValue<false> }>,
  }
}
